name: CI - Build & Push N01683837
on:
  push:
    branches: [ main ]
permissions:
  contents: write   # allow commit back to repo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push multi-arch image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/nginx-n01683837
          TAG=${{ github.sha }}
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMAGE:$TAG -t $IMAGE:latest --push webapp
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Bump Helm values with new tag
        run: |
          sudo apt-get update && sudo apt-get install -y yq
          yq -i '.image.repository=strenv(IMAGE)' helm/nginx-n01683837/values.yaml
          yq -i '.image.tag=strenv(TAG)'       helm/nginx-n01683837/values.yaml
          git config user.name "ci-bot"
          git config user.email "ci@example.com"
          git add helm/nginx-n01683837/values.yaml
          git commit -m "chore: bump image to ${IMAGE}:${TAG}"
          git push
